### ISSUE TITLE
First impression

### ISSUE THREAD

**Issue by eb-so** [the-ginger-geek/flapjack#1]
@the-ginger-geek While the proposed code is mostly a solid encapsulation of our current in-app practices, a major concern arises with the introduction of the findRelative method. This method is problematic as it significantly alters our architectural conventions by allowing direct communication between ViewModels, which goes against our preferred use of middlewares like:

- Pub/Sub
- Shared model
- Services, particularly reactive services
By allowing ViewModels to interact directly, we're complicating testing and violating the principle of ViewModel isolation.

Consider a scenario where ViewModel A triggers a method in ViewModel B upon a button press. Given that both A and B depend on multiple services, testing this interaction becomes complex. We would need to initialize both ViewModel A and B, mock all their services, and then monitor the states of both ViewModels to verify the action's result.

**Comment by the-ginger-geek** [comment]
Initially I thought `findRelative` would be a cool thing to have but I've thought about it for a bit and I agree that it'll add more undesired results than it would make up for in function. The use cases that this is trying to resolve can be rectified with better app architecture.

**Comment by the-ginger-geek** [comment]
Dropped the locator and `findRelative` method [here](https://github.com/the-ginger-geek/flapjack/commit/30e831f6176571a41be6045c28a44562cf8579cb)
